<?php

return [
    'site' => [
        'name' => 'ITQAN Consulting',
        'mark' => 'IC',
        'tagline' => 'Sincere Services. Lasting Results.',
        'email' => 'hello@itqanconsulting.com',
        'address' => 'Dhaka, Bangladesh',
        'description' => 'Practical consulting, technology, and delivery support for businesses in Bangladesh and beyond.',
        'primary_cta' => ['text' => 'Book a Consultation', 'route' => 'contact'],
    ],

    'navigation' => [
        ['label' => 'Home', 'route' => 'home'],
        ['label' => 'Services', 'route' => 'services'],
        ['label' => 'Works', 'route' => 'works'],
        ['label' => 'Catalog', 'route' => 'catalog'],
        ['label' => 'About', 'route' => 'about'],
        ['label' => 'Contact', 'route' => 'contact'],
    ],

    'social_links' => [
        [
            'platform' => 'linkedin',
            'label' => 'ITQAN on LinkedIn',
            'url' => '#',
            'svg' => '<path d="M4.98 3.5C4.98 4.88 3.86 6 2.5 6S0 4.88 0 3.5 1.12 1 2.5 1s2.48 1.12 2.48 2.5zM.36 8.1h4.28V23H.36V8.1zM7.55 8.1h4.1v2.04h.06c.57-1.08 1.96-2.22 4.03-2.22 4.31 0 5.1 2.84 5.1 6.53V23h-4.27v-7.58c0-1.8-.03-4.12-2.51-4.12-2.51 0-2.9 1.96-2.9 3.99V23H7.55V8.1z"/>',
        ],
        [
            'platform' => 'facebook',
            'label' => 'ITQAN on Facebook',
            'url' => '#',
            'svg' => '<path d="M22 12.06C22 6.5 17.52 2 12 2S2 6.5 2 12.06c0 5.02 3.66 9.18 8.44 9.94v-7.03H7.9v-2.91h2.54V9.85c0-2.52 1.49-3.91 3.77-3.91 1.09 0 2.23.2 2.23.2v2.47h-1.25c-1.24 0-1.63.77-1.63 1.57v1.88h2.78l-.44 2.91h-2.34V22C18.34 21.24 22 17.08 22 12.06z"/>',
        ],
        [
            'platform' => 'youtube',
            'label' => 'ITQAN on YouTube',
            'url' => '#',
            'svg' => '<path d="M23.5 6.2a3 3 0 0 0-2.1-2.12C19.55 3.58 12 3.58 12 3.58s-7.55 0-9.4.5A3 3 0 0 0 .5 6.2 31.5 31.5 0 0 0 0 12a31.5 31.5 0 0 0 .5 5.8 3 3 0 0 0 2.1 2.12c1.85.5 9.4.5 9.4.5s7.55 0 9.4-.5a3 3 0 0 0 2.1-2.12A31.5 31.5 0 0 0 24 12a31.5 31.5 0 0 0-.5-5.8zM9.75 15.54V8.46L16 12l-6.25 3.54z"/>',
        ],
        [
            'platform' => 'whatsapp',
            'label' => 'ITQAN on WhatsApp',
            'url' => '#',
            'svg' => '<path d="M20.52 3.48A11.9 11.9 0 0 0 12.06 0C5.49 0 .14 5.34.14 11.91c0 2.1.55 4.16 1.6 5.97L0 24l6.3-1.65a11.9 11.9 0 0 0 5.76 1.47h.01c6.57 0 11.92-5.34 11.92-11.91a11.86 11.86 0 0 0-3.47-8.43zM12.07 21.8h-.01a9.88 9.88 0 0 1-5.04-1.38l-.36-.21-3.74.98 1-3.64-.24-.37a9.86 9.86 0 0 1-1.51-5.27c0-5.46 4.44-9.9 9.91-9.9a9.85 9.85 0 0 1 7 2.9 9.85 9.85 0 0 1 2.9 7c0 5.46-4.45 9.89-9.91 9.89zm5.43-7.4c-.3-.15-1.76-.87-2.03-.97-.27-.1-.47-.15-.67.15-.2.3-.77.97-.94 1.17-.17.2-.35.22-.64.07-.3-.15-1.25-.46-2.38-1.47a8.9 8.9 0 0 1-1.65-2.05c-.17-.3-.02-.46.13-.6.13-.13.3-.35.45-.52.15-.17.2-.3.3-.5.1-.2.05-.37-.02-.52-.07-.15-.67-1.62-.92-2.22-.24-.58-.49-.5-.67-.5h-.57c-.2 0-.52.07-.79.37-.27.3-1.04 1.02-1.04 2.49s1.07 2.89 1.22 3.09c.15.2 2.1 3.2 5.08 4.49.71.31 1.26.49 1.69.63.71.23 1.36.2 1.88.12.57-.08 1.76-.72 2-1.42.25-.7.25-1.3.17-1.42-.07-.13-.27-.2-.57-.35z"/>',
        ],
    ],

    'footer' => [
        'service_links' => ['Consulting', 'Software Development', 'ERP', 'Project Management', 'Business Automation', 'Training'],
        'bottom_left' => 'Consulting | Software Development | ERP | Project Management | Business Automation | Training',
        'copyright' => '© 2026 ITQAN Consulting.',
    ],

    'collections' => [
        'testimonials' => [
            ['title' => 'That saved us a lot of confusion.', 'text' => 'ITQAN helped us organize our system requirements in a way the business and technical team both understood.', 'author' => 'Client Representative', 'role' => 'Operations Team'],
            ['title' => 'They understand the business first.', 'text' => 'They do not just talk about software. They try to understand the actual business first. That made the work easier.', 'author' => 'Business Owner', 'role' => 'Trading Company'],
            ['title' => 'The scope was clear.', 'text' => 'The communication was clear. The scope was clear. We knew what was being done and why.', 'author' => 'Project Stakeholder', 'role' => 'Service Business'],
        ],
        'works' => [
            ['title' => 'Fleetman PLUS', 'pill' => 'Software / Fleet', 'preview_pill' => 'Fleet', 'description' => 'Vehicle, driver, fuel, contract, and reporting control for fleet operations.', 'preview_description' => 'Fleet and operations management system for vehicle, driver, fuel, contract, and reporting control.', 'categories' => ['software', 'process', 'consulting'], 'tags' => ['Operations', 'Reporting', 'Workflow']],
            ['title' => 'HisebGhor', 'pill' => 'Accounting', 'preview_pill' => 'Accounting', 'description' => 'Simple accounting system concept for small businesses with transaction rules and party balances.', 'preview_description' => 'Simple accounting system concept for small businesses with transaction rules, party balances, and reports.', 'categories' => ['software', 'erp', 'consulting'], 'tags' => ['Rules', 'Reports', 'SME']],
            ['title' => 'NextPlay Sportswear', 'pill' => 'E-commerce', 'preview_pill' => 'E-commerce', 'description' => 'Product category, PDP, bulk quote, and custom sportswear ordering experience.', 'preview_description' => 'E-commerce experience for custom sportswear, bulk orders, product pages, and category structure.', 'categories' => ['ecommerce', 'website', 'software'], 'tags' => ['UX', 'Catalog', 'Bulk order']],
            ['title' => 'Business Website Revamp', 'pill' => 'Website Revamp', 'preview_pill' => 'Website', 'description' => 'Website planning, content structure, and UI direction for service businesses and personal brands.', 'preview_description' => 'Website planning, content structure, and UI direction for service businesses and personal brands.', 'categories' => ['website', 'consulting', 'process'], 'tags' => ['Content', 'UI', 'Brand']],
        ],
        'work_filters' => [
            ['label' => 'All', 'value' => 'all'],
            ['label' => 'Software', 'value' => 'software'],
            ['label' => 'ERP', 'value' => 'erp'],
            ['label' => 'Website', 'value' => 'website'],
            ['label' => 'E-commerce', 'value' => 'ecommerce'],
            ['label' => 'Process', 'value' => 'process'],
            ['label' => 'Training', 'value' => 'training'],
            ['label' => 'Consulting', 'value' => 'consulting'],
        ],
        'services' => [
            ['badge' => '01', 'title' => 'Consulting & Business Clarity', 'intro' => 'For businesses with unclear processes, scattered records, delayed reports, or weak control.', 'points' => ['Business process analysis', 'Requirement analysis', 'SOP and workflow documentation', 'Reporting structure'], 'button' => 'Discuss Consulting Work'],
            ['badge' => '02', 'title' => 'Project & Product Support', 'intro' => 'For teams that need better planning, scope control, priorities, tracking, and delivery coordination.', 'points' => ['Project management support', 'Product planning', 'Delivery tracking', 'Project rescue or audit'], 'button' => 'Improve Delivery'],
            ['badge' => '03', 'title' => 'Software & Web Development', 'intro' => 'For businesses that need structured digital tools, web platforms, or custom systems that match the work.', 'points' => ['Business websites', 'Web applications', 'Dashboards and portals', 'Custom business systems'], 'button' => 'Plan a System'],
            ['badge' => '04', 'title' => 'ERP & Automation', 'intro' => 'For teams that want less manual work, better process flow, and more reliable business visibility.', 'points' => ['ERP planning', 'Module design', 'Business automation', 'Reporting automation'], 'button' => 'Explore Automation'],
            ['badge' => '05', 'title' => 'Training & Coaching', 'intro' => 'For companies that want their people to work with better structure, tools, and confidence.', 'points' => ['Project management training', 'Business analysis training', 'Tool-based training', 'Team capacity building'], 'button' => 'Train Your Team'],
            ['badge' => '06', 'title' => 'Dedicated Team Support', 'intro' => 'For businesses that need reliable delivery support through dedicated people across key roles.', 'points' => ['Offshore resource support', 'Dedicated developers', 'PM / BA support', 'Long-term delivery team setup'], 'button' => 'Build a Team'],
        ],
        'service_faqs' => [
            ['question' => 'How do we know which ITQAN service is right for us?', 'summary' => 'You do not need to know the exact service name before contacting us.', 'answer' => ['You can simply share what is happening in your business. Maybe the process is messy, reporting is weak, projects are delayed, people are doing too much manual work, or your current system is not helping enough.', 'We will help you understand the issue first, then suggest the service or support that fits best.']],
            ['question' => 'Do we need to have a clear brief before starting?', 'summary' => 'No.', 'answer' => ['Many clients come with a problem, not a ready brief. That is normal.', 'ITQAN helps organize the problem, ask the right questions, understand the business situation, and prepare a clear direction before execution starts.']],
            ['question' => 'Can ITQAN help if our business process is not documented?', 'summary' => 'Yes.', 'answer' => ['In fact, this is one of the common reasons clients work with us.', 'We can study how the work is currently done, speak with the relevant people, identify gaps, and prepare practical documents, workflows, or system requirements based on the real business process.']],
            ['question' => 'Does ITQAN only provide consulting, or also implementation support?', 'summary' => 'ITQAN provides both consulting and execution support.', 'answer' => ['Depending on the need, we can help with analysis, planning, documentation, system design, software development, ERP support, automation, project management, training, and implementation guidance.', 'The goal is not just to give advice. The goal is to help the work move forward.']],
            ['question' => 'Can ITQAN work with our existing team or vendor?', 'summary' => 'Yes.', 'answer' => ['We can work with your internal team, management team, technical team, or existing software vendor.', 'Sometimes we act as an advisor. Sometimes we support execution. Sometimes we help both sides understand the business requirement better so the work becomes clearer and less delayed.']],
            ['question' => 'What kind of deliverables can we expect?', 'summary' => 'Deliverables depend on the type of work.', 'answer' => ['Common outputs may include process maps, requirement documents, audit findings, improvement plans, project plans, dashboards, reports, system screen flows, training materials, software modules, or implementation support notes.', 'Before starting, we will clarify what will be delivered.']],
            ['question' => 'How does ITQAN usually start a project?', 'summary' => 'We usually start with a discussion.', 'answer' => ['We usually start with a discussion to understand the business problem, current process, team structure, tools, and expected result.', 'After that, we define the scope, approach, timeline, and deliverables.', 'We try to keep the starting point simple and practical.']],
            ['question' => 'Will ITQAN suggest software for every problem?', 'summary' => 'No.', 'answer' => ['We do not push software where a simpler process, better reporting, training, or clearer responsibility can solve the issue.', 'Technology is useful only when it fits the business need. We focus on the problem first, then decide what kind of solution makes sense.']],
            ['question' => 'Can ITQAN support small and growing businesses?', 'summary' => 'Yes.', 'answer' => ['ITQAN works with businesses that need practical support, even if they are not large companies yet.', 'For growing businesses, the focus is usually on creating structure, reducing confusion, improving tracking, and preparing the business for better systems.']],
            ['question' => 'What outcome should we expect after working with ITQAN?', 'summary' => 'You should have better clarity, better structure, and a more practical way to manage the work.', 'answer' => ['The expected outcome may include clearer processes, better reporting, improved delivery control, reduced manual work, better system usage, or stronger decision-making.', 'The exact result depends on the service, but the direction is always the same: make the work easier to understand, manage, and improve.']],
        ],
        'catalog_pages' => [
            ['type' => 'image', 'title' => 'Cover', 'kicker' => 'ITQAN Consulting', 'body' => 'Practical consulting, software planning, delivery support, ERP, automation, websites, and training under one roof.'],
            ['type' => 'image', 'title' => 'Who We Are', 'kicker' => 'Business clarity', 'body' => 'We work with businesses that need clear guidance, better systems, and reliable execution.'],
            ['type' => 'image', 'title' => 'What We Do', 'kicker' => 'Services', 'body' => 'Process analysis, project support, software development, AI strategy, training, and dedicated resources.'],
            ['type' => 'video', 'title' => 'Founder Message', 'kicker' => 'Short video page', 'body' => 'This page is ready for an MP4 catalog page. Add a src and poster in the data array when the real media is uploaded.'],
            ['type' => 'image', 'title' => 'Our Method', 'kicker' => 'Listen. Map. Plan. Build. Support.', 'body' => 'First we understand. Then we build. The method keeps scope clear and delivery practical.'],
            ['type' => 'image', 'title' => 'Contact ITQAN', 'kicker' => 'Next step', 'body' => 'Bring the messy business problem. We will help make it clear.'],
        ],
        'contact_options' => [
            'needs' => ['Not sure yet', 'Business process', 'Software development', 'ERP', 'Website', 'Automation', 'Project management', 'Training', 'Dedicated team'],
            'areas' => ['Business<br>process', 'Software<br>development', 'ERP', 'Website', 'Automation', 'Training'],
            'methods' => ['WhatsApp', 'Email', 'Phone call', 'Google Meet'],
        ],
    ],

    'pages' => [
        'home' => [
            'title' => 'ITQAN Consulting — Website Prototype',
            'meta_description' => 'Responsive website prototype for ITQAN Consulting.',
            'hero' => [
                'label' => 'ITQAN Consulting',
                'title' => 'When business feels <span class="red-text">messy</span>, we help make it <span class="blue-text">clear.</span>',
                'description' => 'ITQAN Consulting supports businesses with practical consulting, software planning, project delivery, automation, ERP, websites, and team support.',
                'chips' => ['No noise.', 'No over-promising.', 'Honest execution.'],
                'buttons' => [
                    ['text' => 'Start a Conversation', 'route' => 'contact', 'class' => 'blue'],
                    ['text' => 'Explore Services', 'route' => 'services', 'class' => ''],
                ],
                'social_label' => 'Connect with ITQAN',
                'ticker' => [
                    'Business process clarity',
                    'Requirements, timeline, and ownership',
                    'Useful dashboards and reporting',
                    'Team alignment and delivery control',
                    'Automation that reduces manual work',
                    'ERP that fits people, data, and business',
                    'Clear execution from idea to support',
                ],
            ],
            'founder' => [
                'label' => 'From the Founder',
                'title' => 'We started ITQAN because many businesses do not fail from lack of effort. They fail from lack of clarity.',
                'paragraphs' => [
                    'I have worked with software teams, business owners, operations teams, product teams, and project teams for many years. One thing is clear.',
                    'Most problems are not only technical. Sometimes the process is unclear. Sometimes the team is confused. Sometimes the software does not match the real work.',
                    'ITQAN Consulting was created to solve these problems in a practical way. We listen first. We understand the business. Then we help with planning, documentation, software, automation, team support, and delivery.',
                ],
                'name' => 'Md Aminul Islam, PMP, CSM',
                'role' => 'Founder & Chief Consultant, ITQAN Consulting',
            ],
            'who' => [
                'label' => 'Who We Are',
                'title' => 'A consulting and technology team for real business problems.',
                'lead' => 'We support companies from idea to implementation. That may include process design, software planning, project management, ERP support, websites, automation, or dedicated team support.',
                'cards' => [
                    ['num' => '01', 'title' => 'Who We Are', 'text' => 'ITQAN works with businesses that need clear guidance, better systems, and reliable execution. We help decide what is right.'],
                    ['num' => '02', 'title' => 'Mission', 'text' => 'To help businesses understand their work, improve their process, and use technology where it truly helps.'],
                    ['num' => '03', 'title' => 'Vision', 'text' => 'To become a trusted consulting and technology partner for growing businesses in Bangladesh and beyond.'],
                ],
            ],
            'problems' => [
                'label' => 'Why ITQAN Exists',
                'title' => 'Because many businesses are working hard, but still feel stuck.',
                'lead' => 'This section is built like a before-and-after board. Each card starts with a real business problem and then shows how ITQAN responds.',
                'items' => [
                    ['problem' => 'The work is happening, but nobody sees the full picture.', 'response' => 'We map the process and make the workflow clear.'],
                    ['problem' => 'The team depends on memory, calls, and scattered files.', 'response' => 'We help organize the work into systems and records.'],
                    ['problem' => 'Software is built, but people do not use it properly.', 'response' => 'We focus on adoption, training, and real business fit.'],
                    ['problem' => 'Management does not get the right reports at the right time.', 'response' => 'We design reporting that helps decisions.'],
                    ['problem' => 'The business wants technology, but the scope is unclear.', 'response' => 'We define the scope before execution starts.'],
                ],
            ],
            'services_preview' => [
                'label' => 'What We Do',
                'title' => 'Consulting, software, and delivery support under one roof.',
                'lead' => 'ITQAN supports the full journey. From business understanding to software delivery. From team setup to process improvement.',
                'items' => [
                    ['num' => '01', 'title' => 'Business Process Analysis', 'text' => 'We turn scattered information into clear process maps, requirements, and documents.'],
                    ['num' => '02', 'title' => 'Project & Product Support', 'text' => 'We help plan, track, and manage work with clear scope, priorities, and delivery control.'],
                    ['num' => '03', 'title' => 'Software Development', 'text' => 'We design and build websites, web applications, ERP modules, dashboards, and custom systems.'],
                    ['num' => '04', 'title' => 'AI Strategy & Automation', 'text' => 'We find where automation can reduce manual work, improve reporting, and save time.'],
                    ['num' => '05', 'title' => 'Training & Capacity Building', 'text' => 'We train teams in project management, business analysis, tools, and practical technology use.'],
                    ['num' => '06', 'title' => 'Dedicated Resource Support', 'text' => 'We help set up skilled delivery teams for ongoing software and operational work.'],
                ],
                'button' => ['text' => 'View All Services', 'route' => 'services'],
            ],
            'working' => [
                'label' => 'Our Way of Working',
                'title' => 'First we understand.<br>Then we build.',
                'intro' => 'A clear process keeps business, management, and technical teams aligned from the beginning.',
                'items' => [
                    ['num' => '1', 'title' => 'Listen', 'text' => 'We sit with you and understand the real problem.'],
                    ['num' => '2', 'title' => 'Map', 'text' => 'We document the process, users, data, and pain points.'],
                    ['num' => '3', 'title' => 'Plan', 'text' => 'We define scope, priority, timeline, and responsibilities.'],
                    ['num' => '4', 'title' => 'Build', 'text' => 'We design, develop, configure, or guide the solution.'],
                    ['num' => '5', 'title' => 'Support', 'text' => 'We help the team use it, improve it, and continue with confidence.'],
                ],
            ],
            'testimonials' => ['label' => 'Client Words', 'title' => 'People remember clear work.'],
            'works_preview' => ['label' => 'Works', 'title' => 'A few problems we helped solve.', 'button' => ['text' => 'View Our Works', 'route' => 'works']],
            'cta' => ['title' => 'Have a business problem that needs clear thinking?', 'text' => 'Let’s talk first. No pressure. No hard selling. We will understand your situation and suggest a practical next step.', 'button' => ['text' => 'Contact ITQAN', 'route' => 'contact']],
        ],
        'about' => [
            'title' => 'About ITQAN Consulting',
            'meta_description' => 'A consulting-led technology partner built around real business needs.',
            'hero' => ['label' => 'About ITQAN', 'title' => 'A consulting-led technology partner built around real business needs.', 'description' => 'ITQAN Consulting helps businesses understand their work, improve their process, and use technology where it truly helps.', 'buttons' => [['text' => 'Talk to Us', 'route' => 'contact', 'class' => 'blue']]],
            'story' => ['label' => 'Our Story', 'title' => 'We do not start with software. We start with the work.', 'paragraphs' => ['Many organizations have hardworking people, but the process is unclear. Reports come late. Requirements change without control. Software is requested before the real problem is understood.', 'ITQAN was built to help in these moments. We listen, document, guide, and execute. The goal is not to make things bigger. The goal is to make work easier to understand and easier to manage.']],
            'beliefs' => ['label' => 'What We Believe', 'title' => 'Clear thinking is part of the delivery.', 'items' => [['num' => '01', 'title' => 'Clarity before execution', 'text' => 'Scope must be understood before work starts.'], ['num' => '02', 'title' => 'Simple where simple works', 'text' => 'Not every problem needs a large system.'], ['num' => '03', 'title' => 'Fit the real business', 'text' => 'Tools should match how people actually work.'], ['num' => '04', 'title' => 'Honest advice', 'text' => 'We say what is useful, even when a smaller fix is enough.']]],
            'mission_vision' => [['num' => 'Mission', 'title' => 'To make business work clearer, smarter, and easier to manage.', 'text' => 'We focus on clear documents, useful systems, better reports, better coordination, and better control.'], ['num' => 'Vision', 'title' => 'To become a trusted consulting and technology partner for growing businesses.', 'text' => 'We want ITQAN to be known for sincerity, clarity, and useful delivery in Bangladesh and beyond.']],
            'cta' => ['title' => 'Need a practical partner for your next system or project?', 'text' => 'Share where the work feels stuck. We will help organize the next step.', 'button' => ['text' => 'Book a Consultation', 'route' => 'contact']],
        ],
        'services' => [
            'title' => 'Services | ITQAN Consulting',
            'meta_description' => 'Services for businesses that need clarity, systems, and reliable execution.',
            'hero' => ['label' => 'Services', 'title' => 'Services for businesses that need clarity, systems, and reliable execution.', 'description' => 'From business analysis to software delivery, ITQAN supports the full journey.', 'buttons' => [['text' => 'Start a Conversation', 'route' => 'contact', 'class' => 'blue'], ['text' => 'View Service Areas', 'url' => '#service-areas', 'class' => '']]],
            'faq_title' => 'Common Questions',
            'cta' => ['title' => 'Not sure which service you need?', 'text' => 'Bring the problem. We will help organize the right scope.', 'button' => ['text' => 'Start a Conversation', 'route' => 'contact']],
        ],
        'works' => [
            'title' => 'Works | ITQAN Consulting',
            'meta_description' => 'A few problems ITQAN helped solve.',
            'hero' => ['label' => 'Works', 'title' => 'A few problems we helped solve.', 'description' => 'Our work is not only about screens. It is about making business operations easier to see, manage, and improve.', 'buttons' => [['text' => 'Discuss Your Project', 'route' => 'contact', 'class' => 'blue']]],
        ],
        'catalog' => [
            'title' => 'Digital Catalog | ITQAN Consulting',
            'meta_description' => 'Read the ITQAN Digital Catalog.',
            'hero' => ['label' => 'Digital Catalog', 'title' => 'Read the ITQAN Digital Catalog.', 'description' => 'Browse our consulting, technology, and delivery services in a smooth page-by-page format.', 'buttons' => [['text' => 'Open Catalog', 'url' => '#catalog-viewer', 'class' => 'blue']]],
        ],
        'contact' => [
            'title' => 'Contact | ITQAN Consulting',
            'meta_description' => 'Let’s talk about what you are trying to fix.',
            'hero' => ['label' => 'Contact', 'title' => 'Let’s talk about what you are trying to fix.', 'description' => 'You do not need a perfect brief before contacting us. Share what is happening in your business. We will help you organize the problem.'],
            'side_note' => ['label' => 'What happens next?', 'title' => 'No hard selling. No pressure.', 'text' => 'We read your message and ask a few useful questions. Then we suggest a practical next step.', 'steps' => ['We read your message.', 'We ask a few useful questions.', 'We suggest a practical next step.']],
            'cta' => ['title' => 'Send the messy version first.', 'text' => 'We can organize it together.', 'button' => ['text' => 'hello@itqanconsulting.com', 'url' => 'mailto:hello@itqanconsulting.com']],
        ],
    ],
];
