<?php

return [
    'path' => 'starpmaminul',
    'database_connection' => 'starpmaminul',

    'admin' => [
        'name' => env('STARPMAMINUL_ADMIN_NAME', 'Portfolio Admin'),
        'email' => env('STARPMAMINUL_ADMIN_EMAIL', 'admin@aminulislam.com'),
        'password' => env('STARPMAMINUL_ADMIN_PASSWORD', 'Admin@12345'),
    ],

    'sections' => [
        'site' => [
            'label' => 'Site & Header',
            'description' => 'Page metadata, branding, navigation and the header call to action.',
            'icon' => 'layout',
            'defaults' => [
                'page_title' => 'Md Aminul Islam, PMP, CSM — Digital Resume',
                'loader_tagline' => 'Project · Product · ERP · PMO',
                'meta_description' => 'Md Aminul Islam, PMP, CSM — Project Delivery, ERP, PMO, Product and Digital Transformation Leader.',
                'brand_logo' => null,
                'brand_initials' => 'AMI',
                'brand_name' => 'Md Aminul Islam',
                'brand_credentials' => 'PMP® · CSM®',
                'navigation' => [
                    ['label' => 'About', 'target' => '#about'],
                    ['label' => 'Impact', 'target' => '#impact'],
                    ['label' => 'Work', 'target' => '#work'],
                    ['label' => 'Journey', 'target' => '#journey'],
                    ['label' => 'Voices', 'target' => '#voices'],
                ],
                'mobile_navigation' => [
                    ['label' => 'About', 'target' => '#about'],
                    ['label' => 'Impact', 'target' => '#impact'],
                    ['label' => 'Selected work', 'target' => '#work'],
                    ['label' => 'Career journey', 'target' => '#journey'],
                    ['label' => 'Testimonials', 'target' => '#voices'],
                    ['label' => 'Contact', 'target' => '#contact'],
                ],
                'header_cta_text' => 'Start a conversation',
                'header_cta_email' => 'aminul@itqanconsulting.com',
                'notes_title' => 'Content replacement notes',
                'notes_description' => 'Turn on edit markers to see the few items that still need your final input.',
                'notes' => [
                    ['text' => '1. Add your final professional portrait.'],
                    ['text' => '2. Confirm the public availability message.'],
                    ['text' => '3. Add a downloadable CV file when ready.'],
                    ['text' => '4. Optional: replace illustrative dashboard art with approved project screenshots.'],
                ],
                'notes_button' => 'Toggle edit markers',
            ],
            'fields' => [
                ['name' => 'page_title', 'label' => 'Browser page title', 'type' => 'text'],
                ['name' => 'loader_tagline', 'label' => 'Loading screen tagline', 'type' => 'text'],
                ['name' => 'meta_description', 'label' => 'Meta description', 'type' => 'textarea', 'rows' => 3],
                [
                    'name' => 'brand_logo',
                    'label' => 'Complete header logo',
                    'type' => 'image',
                    'help' => 'Upload one complete logo image containing the mark, name and credentials. Recommended: transparent PNG or WebP with a wide horizontal layout.',
                    'remove_label' => 'Remove the uploaded logo and use the AMI, name and credentials fallback.',
                ],
                ['name' => 'brand_initials', 'label' => 'Brand initials', 'type' => 'text'],
                ['name' => 'brand_name', 'label' => 'Brand name', 'type' => 'text'],
                ['name' => 'brand_credentials', 'label' => 'Brand credentials', 'type' => 'text'],
                [
                    'name' => 'navigation', 'label' => 'Header navigation', 'type' => 'collection',
                    'fields' => [
                        ['name' => 'label', 'label' => 'Label', 'type' => 'text'],
                        ['name' => 'target', 'label' => 'Section target', 'type' => 'text', 'rules' => ['starts_with:#'], 'help' => 'Keep the existing #section format.'],
                    ],
                ],
                [
                    'name' => 'mobile_navigation', 'label' => 'Mobile navigation', 'type' => 'collection',
                    'fields' => [
                        ['name' => 'label', 'label' => 'Label', 'type' => 'text'],
                        ['name' => 'target', 'label' => 'Section target', 'type' => 'text', 'rules' => ['starts_with:#']],
                    ],
                ],
                ['name' => 'header_cta_text', 'label' => 'Header button text', 'type' => 'text'],
                ['name' => 'header_cta_email', 'label' => 'Header contact email', 'type' => 'email'],
                ['name' => 'notes_title', 'label' => 'Content notes title', 'type' => 'text'],
                ['name' => 'notes_description', 'label' => 'Content notes description', 'type' => 'textarea', 'rows' => 3],
                [
                    'name' => 'notes', 'label' => 'Content notes', 'type' => 'collection',
                    'fields' => [['name' => 'text', 'label' => 'Note', 'type' => 'text']],
                ],
                ['name' => 'notes_button', 'label' => 'Content notes button', 'type' => 'text'],
            ],
        ],

        'hero' => [
            'label' => 'Hero',
            'description' => 'Opening message, profile details, portrait and key headline statistics.',
            'icon' => 'sparkles',
            'defaults' => [
                'availability' => 'Available for selected consulting and leadership engagements',
                'name_line_one' => 'Md Aminul',
                'name_line_two' => 'Islam.',
                'role_label' => 'What I do',
                'role_primary' => 'Project delivery and digital transformation leader.',
                'role_secondary' => 'I bring structure to ERP, PMO, product, fintech and complex technology programs.',
                'primary_button' => 'Explore selected work',
                'secondary_button' => 'Print / Save as PDF',
                'portrait' => null,
                'portrait_alt' => 'Professional portrait of Md Aminul Islam',
                'profile_name' => 'Md Aminul Islam, PMP®, CSM®',
                'profile_role' => 'Founder & Managing Consultant, ITQAN Consulting',
                'profile_number' => '01 / PROFILE',
                'stats' => [
                    ['value' => '15+', 'label' => 'Years in delivery'],
                    ['value' => '90K+', 'label' => 'Users impacted'],
                    ['value' => '38', 'label' => 'Concurrent projects'],
                ],
                'scroll_text' => 'Scroll through the story',
                'location_text' => 'Dhaka, Bangladesh · Serving teams internationally',
            ],
            'fields' => [
                ['name' => 'availability', 'label' => 'Availability message', 'type' => 'text'],
                ['name' => 'name_line_one', 'label' => 'Name — first line', 'type' => 'text'],
                ['name' => 'name_line_two', 'label' => 'Name — outlined line', 'type' => 'text'],
                ['name' => 'role_label', 'label' => 'Role label', 'type' => 'text'],
                ['name' => 'role_primary', 'label' => 'Primary role statement', 'type' => 'text'],
                ['name' => 'role_secondary', 'label' => 'Supporting role statement', 'type' => 'textarea', 'rows' => 3],
                ['name' => 'primary_button', 'label' => 'Primary button text', 'type' => 'text'],
                ['name' => 'secondary_button', 'label' => 'Print button text', 'type' => 'text'],
                ['name' => 'portrait', 'label' => 'Professional portrait', 'type' => 'image', 'help' => 'Recommended: high-resolution vertical portrait. Leave empty to keep the template illustration.'],
                ['name' => 'portrait_alt', 'label' => 'Portrait alternative text', 'type' => 'text'],
                ['name' => 'profile_name', 'label' => 'Portrait nameplate', 'type' => 'text'],
                ['name' => 'profile_role', 'label' => 'Portrait role', 'type' => 'text'],
                ['name' => 'profile_number', 'label' => 'Portrait index', 'type' => 'text'],
                [
                    'name' => 'stats', 'label' => 'Floating statistics', 'type' => 'collection',
                    'fields' => [
                        ['name' => 'value', 'label' => 'Value', 'type' => 'text'],
                        ['name' => 'label', 'label' => 'Label', 'type' => 'text'],
                    ],
                ],
                ['name' => 'scroll_text', 'label' => 'Scroll cue', 'type' => 'text'],
                ['name' => 'location_text', 'label' => 'Location line', 'type' => 'text'],
            ],
        ],

        'ticker' => [
            'label' => 'Expertise Ticker',
            'description' => 'The continuously scrolling expertise labels below the hero.',
            'icon' => 'repeat',
            'defaults' => [
                'items' => [
                    ['label' => 'Project & Portfolio Delivery'],
                    ['label' => 'ERP Implementation'],
                    ['label' => 'PMO Governance'],
                    ['label' => 'Product Delivery'],
                    ['label' => 'Fintech & Microfinance Systems'],
                    ['label' => 'Business Analysis'],
                    ['label' => 'Team Development'],
                ],
            ],
            'fields' => [
                [
                    'name' => 'items', 'label' => 'Ticker items', 'type' => 'collection',
                    'fields' => [['name' => 'label', 'label' => 'Item text', 'type' => 'text']],
                ],
            ],
        ],

        'philosophy' => [
            'label' => 'Leadership Philosophy',
            'description' => 'The philosophy statement, manifesto and animated leadership-value orbit.',
            'icon' => 'compass',
            'defaults' => [
                'section_index' => '01 · Leadership philosophy',
                'title_prefix' => 'Every role is an',
                'title_emphasis' => 'Amanah.',
                'description' => 'I try to lead with sincerity, fairness and ownership. The work must be useful. The process must be honest. And people should become stronger because we worked together.',
                'manifesto_mark' => '01',
                'manifesto_intro' => 'At the center is one commitment:',
                'manifesto_core' => 'Serve Well',
                'manifesto_body' => 'Around it are Ikhlās, Amanah, Adl and Ihsān—so the work is useful, responsible, fair and excellent; and, in shā’ Allāh, pleasing to Allah SWT.',
                'orbit_text' => 'SINCERITY · TRUST · FAIRNESS · EXCELLENCE · SERVICE · RESPONSIBILITY ·',
                'center_label' => 'Centered on',
                'center_line_one' => 'Serve',
                'center_line_two' => 'Well',
                'center_caption_line_one' => 'Useful work.',
                'center_caption_line_two' => 'Honest process.',
                'interaction_caption' => 'Move to explore',
                'values' => [
                    ['name' => 'Ikhlās', 'meaning' => 'Sincerity', 'detail' => 'Pure intention'],
                    ['name' => 'Amanah', 'meaning' => 'Trust', 'detail' => 'Owned responsibly'],
                    ['name' => 'Adl', 'meaning' => 'Fairness', 'detail' => 'Balanced judgment'],
                    ['name' => 'Ihsān', 'meaning' => 'Excellence', 'detail' => 'Better than required'],
                ],
            ],
            'fields' => [
                ['name' => 'section_index', 'label' => 'Section label', 'type' => 'text'],
                ['name' => 'title_prefix', 'label' => 'Title', 'type' => 'text'],
                ['name' => 'title_emphasis', 'label' => 'Emphasized title word', 'type' => 'text'],
                ['name' => 'description', 'label' => 'Description', 'type' => 'textarea', 'rows' => 4],
                ['name' => 'manifesto_mark', 'label' => 'Manifesto number', 'type' => 'text'],
                ['name' => 'manifesto_intro', 'label' => 'Manifesto opening', 'type' => 'text'],
                ['name' => 'manifesto_core', 'label' => 'Manifesto highlighted commitment', 'type' => 'text'],
                ['name' => 'manifesto_body', 'label' => 'Manifesto supporting text', 'type' => 'textarea', 'rows' => 4],
                ['name' => 'orbit_text', 'label' => 'Orbit text', 'type' => 'text', 'help' => 'Use short uppercase words separated by dots for the circular label.'],
                ['name' => 'center_label', 'label' => 'Center label', 'type' => 'text'],
                ['name' => 'center_line_one', 'label' => 'Center text — first line', 'type' => 'text'],
                ['name' => 'center_line_two', 'label' => 'Center text — second line', 'type' => 'text'],
                ['name' => 'center_caption_line_one', 'label' => 'Center caption — first line', 'type' => 'text'],
                ['name' => 'center_caption_line_two', 'label' => 'Center caption — second line', 'type' => 'text'],
                ['name' => 'interaction_caption', 'label' => 'Interaction hint', 'type' => 'text'],
                [
                    'name' => 'values', 'label' => 'Leadership values', 'type' => 'collection',
                    'fields' => [
                        ['name' => 'name', 'label' => 'Value', 'type' => 'text'],
                        ['name' => 'meaning', 'label' => 'Meaning', 'type' => 'text'],
                        ['name' => 'detail', 'label' => 'Hover detail', 'type' => 'text'],
                    ],
                ],
            ],
        ],

        'overview' => [
            'label' => 'Professional Overview',
            'description' => 'Professional summary and core capability list.',
            'icon' => 'list',
            'defaults' => [
                'section_index' => '02 · Professional overview',
                'title' => 'I turn complexity into controlled delivery.',
                'description' => 'Organizations rarely struggle because people are not trying. More often, priorities are unclear, ownership overlaps, requirements keep moving, and leaders cannot see what is really happening. That is where I work best.',
                'capabilities' => [
                    ['title' => 'Project, program & portfolio delivery', 'description' => 'Planning, governance, risk control, stakeholder alignment and execution across complex technology portfolios.'],
                    ['title' => 'ERP & enterprise transformation', 'description' => 'Business-process alignment, requirements, phased rollout, data migration, adoption and cross-functional coordination.'],
                    ['title' => 'PMO setup & project recovery', 'description' => 'Practical reporting, delivery standards, dashboards, budget controls and intervention for delayed or unclear projects.'],
                    ['title' => 'Product & digital platform delivery', 'description' => 'Turning business needs into roadmaps, structured requirements, priorities, release plans and usable digital experiences.'],
                    ['title' => 'Fintech & microfinance systems', 'description' => 'Experience connecting finance, operations, user workflows and technology across microfinance, banking and payment-related platforms.'],
                ],
            ],
            'fields' => [
                ['name' => 'section_index', 'label' => 'Section label', 'type' => 'text'],
                ['name' => 'title', 'label' => 'Title', 'type' => 'text'],
                ['name' => 'description', 'label' => 'Introduction', 'type' => 'textarea', 'rows' => 5],
                [
                    'name' => 'capabilities', 'label' => 'Capabilities', 'type' => 'collection',
                    'fields' => [
                        ['name' => 'title', 'label' => 'Capability title', 'type' => 'text'],
                        ['name' => 'description', 'label' => 'Capability description', 'type' => 'textarea', 'rows' => 3],
                    ],
                ],
            ],
        ],

        'impact' => [
            'label' => 'Scale & Impact',
            'description' => 'Section introduction and animated metric cards.',
            'icon' => 'chart',
            'defaults' => [
                'section_index' => '03 · Scale & impact',
                'title' => 'A career measured in delivery, not job titles.',
                'description' => 'From nationwide ERP rollout to PMO leadership and digital products, the common thread has been simple: make work visible, align people, reduce confusion and deliver responsibly.',
                'metrics' => [
                    ['prefix' => '', 'value' => '15', 'suffix' => '+', 'decimals' => '0', 'description' => 'Years across technology, finance, manufacturing, project delivery and consulting.'],
                    ['prefix' => '', 'value' => '90', 'suffix' => 'K+', 'decimals' => '0', 'description' => 'Users served by the enterprise ERP program delivered for BRAC operations.'],
                    ['prefix' => '', 'value' => '3200', 'suffix' => '+', 'decimals' => '0', 'description' => 'Branches and operational locations reached through large-scale rollout.'],
                    ['prefix' => '', 'value' => '3000', 'suffix' => '+', 'decimals' => '0', 'description' => 'Transactions per second supported by the high-volume enterprise platform.'],
                    ['prefix' => '', 'value' => '38', 'suffix' => '', 'decimals' => '0', 'description' => 'Concurrent projects managed within a diverse portfolio of large, medium and small initiatives.'],
                    ['prefix' => '$', 'value' => '9.14', 'suffix' => 'M', 'decimals' => '2', 'description' => 'Approximate value of the flagship enterprise ERP implementation program.'],
                    ['prefix' => '$', 'value' => '639', 'suffix' => 'K+', 'decimals' => '0', 'description' => 'Cost efficiency identified through the BRAC University SAP audit engagement.'],
                    ['prefix' => '', 'value' => '300', 'suffix' => '+', 'decimals' => '0', 'description' => 'Professionals trained or mentored in project management, Agile, BA and leadership.'],
                ],
            ],
            'fields' => [
                ['name' => 'section_index', 'label' => 'Section label', 'type' => 'text'],
                ['name' => 'title', 'label' => 'Title', 'type' => 'text'],
                ['name' => 'description', 'label' => 'Introduction', 'type' => 'textarea', 'rows' => 4],
                [
                    'name' => 'metrics', 'label' => 'Impact metrics', 'type' => 'collection',
                    'fields' => [
                        ['name' => 'prefix', 'label' => 'Prefix', 'type' => 'text', 'placeholder' => '$'],
                        ['name' => 'value', 'label' => 'Number', 'type' => 'number', 'step' => 'any'],
                        ['name' => 'suffix', 'label' => 'Suffix', 'type' => 'text', 'placeholder' => 'K+'],
                        ['name' => 'decimals', 'label' => 'Decimal places', 'type' => 'number', 'step' => '1', 'rules' => ['integer', 'min:0', 'max:4']],
                        ['name' => 'description', 'label' => 'Description', 'type' => 'textarea', 'rows' => 3],
                    ],
                ],
            ],
        ],

        'work' => [
            'label' => 'Selected Work',
            'description' => 'Selected project cards and their slide-out project details.',
            'icon' => 'briefcase',
            'defaults' => [
                'section_index' => '04 · Selected work',
                'title' => 'Work that changed how organizations operate.',
                'description' => 'A focused selection from enterprise systems, PMO transformation, digital platforms, audits and international operations.',
                'drawer_placeholder_label' => 'Selected engagement',
                'drawer_placeholder_title' => 'Project title',
                'drawer_placeholder_description' => 'Project description.',
                'projects' => [
                    [
                        'key' => 'brac', 'label' => 'Flagship program · ERP', 'title' => 'BRAC ERP',
                        'summary' => 'A multi-module enterprise platform supporting nationwide microfinance and core operations at exceptional scale.',
                        'tags' => '90,000+ users|3,200+ branches|11 modules|3,000+ TPS',
                        'drawer_label' => 'Flagship program · Enterprise ERP',
                        'drawer_intro' => 'A multi-year transformation program supporting microfinance, finance, HR, inventory and other critical operations across a nationwide network.',
                        'details' => [
                            ['label' => 'Role', 'text' => 'Project Manager → PMO leadership. Joined as the first dedicated Project Manager for the ERP program and helped scale the project-management function.'],
                            ['label' => 'Scale', 'text' => '90,000+ users, 3,200+ branches, 11 modules and more than 3,000 transactions per second.'],
                            ['label' => 'Contribution', 'text' => 'Program planning, stakeholder coordination, risk and issue management, business analysis support, phased rollout, data validation and governance.'],
                            ['label' => 'Outcome', 'text' => 'Stronger delivery visibility, improved coordination between business and technology teams, and controlled rollout with reduced operational disruption.'],
                        ],
                    ],
                    [
                        'key' => 'cartup', 'label' => 'E-commerce · Product delivery', 'title' => 'CartUp.com',
                        'summary' => 'PMO governance, product lifecycle support, Agile delivery and release coordination for a major e-commerce platform.',
                        'tags' => 'PMO setup|Product releases|Agile',
                        'drawer_label' => 'E-commerce · Product and delivery',
                        'drawer_intro' => 'PMO and product-delivery support for an e-commerce platform within US-Bangla Group.',
                        'details' => [
                            ['label' => 'Role', 'text' => 'Head of PMO, supporting governance, team mentoring, project risk, stakeholder communication and delivery standards.'],
                            ['label' => 'Product work', 'text' => 'Requirements, feature ideation, prioritization, release planning, campaign readiness, retrospectives and delivery improvement.'],
                            ['label' => 'Approach', 'text' => 'Connected business priorities, product decisions and technical execution through visible planning and regular coordination.'],
                        ],
                    ],
                    [
                        'key' => 'sap', 'label' => 'Enterprise audit', 'title' => 'SAP Audit',
                        'summary' => 'System and implementation review for BRAC University that identified significant cost efficiency.',
                        'tags' => '~$639K savings|Audit',
                        'drawer_label' => 'Enterprise system review',
                        'drawer_intro' => 'A structured review of the SAP engagement and implementation approach for BRAC University.',
                        'details' => [
                            ['label' => 'Focus', 'text' => 'Review of scope, implementation concerns, costs and practical fit.'],
                            ['label' => 'Impact', 'text' => 'The engagement identified approximately USD 639K in cost efficiency.'],
                            ['label' => 'Value', 'text' => 'Helped leadership make a better-informed enterprise-system decision.'],
                        ],
                    ],
                    [
                        'key' => 'pmo', 'label' => 'Governance · CMMI', 'title' => 'PMO Transformation',
                        'summary' => 'JIRA-connected KPI visibility, delivery standards, budgeting discipline, reporting and CMMI Level III practices.',
                        'tags' => '38 projects|12-member PMO',
                        'drawer_label' => 'PMO · Governance · CMMI',
                        'drawer_intro' => 'Building delivery systems that make projects easier to govern, understand and improve.',
                        'details' => [
                            ['label' => 'BRAC IT', 'text' => 'Managed a 38-project portfolio, introduced JIRA-connected dashboards, reporting, resource planning and delivery-development practices.'],
                            ['label' => 'Synesis IT', 'text' => 'Created a PMO charter, strengthened project budgeting, delivery KPIs and CMMI-aligned practices.'],
                            ['label' => 'TechnoNext', 'text' => 'Supported centralized PMO frameworks, Agile adoption, team mentoring and e-commerce delivery governance.'],
                            ['label' => 'Capability', 'text' => 'Led and developed project managers, program managers and coordinators across different organizational settings.'],
                        ],
                    ],
                    [
                        'key' => 'global', 'label' => 'International operations', 'title' => 'Across Borders',
                        'summary' => 'ERP rollout in Africa and manufacturing automation work in China, connecting operations, inventory and technology teams.',
                        'tags' => 'China|Sierra Leone|Liberia',
                        'drawer_label' => 'International and cross-border work',
                        'drawer_intro' => 'Delivery experience across different operational cultures and business environments.',
                        'details' => [
                            ['label' => 'China', 'text' => 'Business and manufacturing operations, including automation and inventory-related solutions for custom-gift production serving international clients.'],
                            ['label' => 'Sierra Leone & Liberia', 'text' => 'Supported ERP rollout and stakeholder coordination in multi-country environments.'],
                            ['label' => 'Bangladesh', 'text' => 'Enterprise, government, NGO, education, financial-services and technology delivery.'],
                            ['label' => 'Lesson', 'text' => 'Technology works best when the delivery model respects local workflows, people and operational reality.'],
                        ],
                    ],
                ],
            ],
            'fields' => [
                ['name' => 'section_index', 'label' => 'Section label', 'type' => 'text'],
                ['name' => 'title', 'label' => 'Title', 'type' => 'text'],
                ['name' => 'description', 'label' => 'Introduction', 'type' => 'textarea', 'rows' => 4],
                ['name' => 'drawer_placeholder_label', 'label' => 'Project drawer placeholder label', 'type' => 'text'],
                ['name' => 'drawer_placeholder_title', 'label' => 'Project drawer placeholder title', 'type' => 'text'],
                ['name' => 'drawer_placeholder_description', 'label' => 'Project drawer placeholder description', 'type' => 'text'],
                [
                    'name' => 'projects', 'label' => 'Project cards', 'type' => 'collection',
                    'fields' => [
                        ['name' => 'key', 'label' => 'Internal key', 'type' => 'text', 'rules' => ['alpha_dash', 'distinct'], 'help' => 'Keep unique. Used only for opening the project drawer.'],
                        ['name' => 'label', 'label' => 'Card label', 'type' => 'text'],
                        ['name' => 'title', 'label' => 'Project title', 'type' => 'text'],
                        ['name' => 'summary', 'label' => 'Card summary', 'type' => 'textarea', 'rows' => 3],
                        ['name' => 'tags', 'label' => 'Card tags', 'type' => 'text', 'help' => 'Separate tags with |.'],
                        ['name' => 'drawer_label', 'label' => 'Drawer label', 'type' => 'text'],
                        ['name' => 'drawer_intro', 'label' => 'Drawer introduction', 'type' => 'textarea', 'rows' => 3],
                        [
                            'name' => 'details', 'label' => 'Drawer details', 'type' => 'collection',
                            'fields' => [
                                ['name' => 'label', 'label' => 'Detail label', 'type' => 'text'],
                                ['name' => 'text', 'label' => 'Detail text', 'type' => 'textarea', 'rows' => 3],
                            ],
                        ],
                    ],
                ],
            ],
        ],

        'case_study' => [
            'label' => 'Signature Case Study',
            'description' => 'Case study introduction, dashboard labels and delivery steps.',
            'icon' => 'file',
            'defaults' => [
                'section_index' => '05 · Signature case study',
                'title' => 'BRAC ERP. Nationwide scale, controlled one step at a time.',
                'description' => 'The program required far more than software delivery. It needed business understanding, structured decisions, phased execution, user validation and patient coordination across a large organization.',
                'dashboard_label' => 'Program delivery view · illustrative',
                'kpis' => [
                    ['value' => '90K+', 'label' => 'Active users'],
                    ['value' => '3.2K+', 'label' => 'Branches'],
                    ['value' => '11', 'label' => 'ERP modules'],
                ],
                'chart_title' => 'Illustrative rollout wave progression',
                'steps' => [
                    ['title' => 'Structure the delivery', 'description' => 'Program-level reporting, regular reviews and clearer visibility across modules gave leadership a practical view of progress, risks and decisions.'],
                    ['title' => 'Align business and technology', 'description' => 'Continuous engagement connected real branch workflows, enterprise requirements, technical feasibility and stakeholder expectations.'],
                    ['title' => 'Prioritize and validate', 'description' => 'Requirements were organized into phases, supported by demos, prototypes, user feedback, field insight and controlled acceptance.'],
                    ['title' => 'Roll out in waves', 'description' => 'Pilots, data validation, reconciliation and phased deployment reduced operational risk while the platform expanded nationwide.'],
                    ['title' => 'Build capability around the system', 'description' => 'The project management function grew from the first dedicated role into a broader PMO, embedding planning, risk, communication and governance practices.'],
                ],
            ],
            'fields' => [
                ['name' => 'section_index', 'label' => 'Section label', 'type' => 'text'],
                ['name' => 'title', 'label' => 'Title', 'type' => 'text'],
                ['name' => 'description', 'label' => 'Introduction', 'type' => 'textarea', 'rows' => 5],
                ['name' => 'dashboard_label', 'label' => 'Dashboard label', 'type' => 'text'],
                [
                    'name' => 'kpis', 'label' => 'Dashboard KPIs', 'type' => 'collection',
                    'fields' => [
                        ['name' => 'value', 'label' => 'Value', 'type' => 'text'],
                        ['name' => 'label', 'label' => 'Label', 'type' => 'text'],
                    ],
                ],
                ['name' => 'chart_title', 'label' => 'Chart caption', 'type' => 'text'],
                [
                    'name' => 'steps', 'label' => 'Case study steps', 'type' => 'collection',
                    'fields' => [
                        ['name' => 'title', 'label' => 'Step title', 'type' => 'text'],
                        ['name' => 'description', 'label' => 'Step description', 'type' => 'textarea', 'rows' => 3],
                    ],
                ],
            ],
        ],

        'journey' => [
            'label' => 'Career Journey',
            'description' => 'Career timeline introduction and timeline entries.',
            'icon' => 'route',
            'defaults' => [
                'section_index' => '06 · Career journey',
                'title' => 'Built from operations. Grown through delivery. Now focused on advisory and impact.',
                'description' => 'The titles changed. The core work stayed familiar: understand the problem, organize people and decisions, then see the work through.',
                'items' => [
                    ['period' => '2025 — Now', 'role' => 'Founder & Managing Consultant', 'company' => 'ITQAN Consulting', 'intro' => 'Helping organizations with', 'highlight' => 'project delivery, ERP, PMO, business analysis, product support, software planning, audit, recovery and capability development.'],
                    ['period' => '2024 — 2025', 'role' => 'Head of PMO', 'company' => 'TechnoNext · US-Bangla Group', 'intro' => 'Supported centralized PMO setup and worked closely with the', 'highlight' => 'CartUp e-commerce product lifecycle, release planning, risk, governance and delivery improvement.'],
                    ['period' => '2024', 'role' => 'GM & Head of Project Management', 'company' => 'Synesis IT PLC', 'intro' => 'Led a team across strategic projects, introduced a PMO charter, project budgeting, delivery KPIs and', 'highlight' => 'CMMI-aligned management practices.'],
                    ['period' => '2017 — 2024', 'role' => 'Acting Head of Project Management', 'company' => 'BRAC IT', 'intro' => 'Progressed through project leadership roles, managed a portfolio of 38 projects, helped deliver the flagship ERP and built', 'highlight' => 'PMO, JIRA, CMMI and team-development practices.'],
                    ['period' => 'Earlier', 'role' => 'Business, BA & Project Foundations', 'company' => 'China · Ergo Ventures · United Finance', 'intro' => 'Early work across financial operations, business analysis, software projects, client management and manufacturing operations created a practical bridge between', 'highlight' => 'business reality and technology delivery.'],
                ],
            ],
            'fields' => [
                ['name' => 'section_index', 'label' => 'Section label', 'type' => 'text'],
                ['name' => 'title', 'label' => 'Title', 'type' => 'text'],
                ['name' => 'description', 'label' => 'Introduction', 'type' => 'textarea', 'rows' => 4],
                [
                    'name' => 'items', 'label' => 'Timeline entries', 'type' => 'collection',
                    'fields' => [
                        ['name' => 'period', 'label' => 'Period', 'type' => 'text'],
                        ['name' => 'role', 'label' => 'Role', 'type' => 'text'],
                        ['name' => 'company', 'label' => 'Company', 'type' => 'text'],
                        ['name' => 'intro', 'label' => 'Description introduction', 'type' => 'textarea', 'rows' => 3],
                        ['name' => 'highlight', 'label' => 'Bold closing text', 'type' => 'textarea', 'rows' => 3],
                    ],
                ],
            ],
        ],

        'operating_system' => [
            'label' => 'How I Work',
            'description' => 'Operating principles and the four-step delivery approach.',
            'icon' => 'settings',
            'defaults' => [
                'section_index' => '07 · How I work',
                'title' => 'Clarity first. Then structure. Then disciplined execution.',
                'description' => 'I do not begin with a fixed answer. I begin by understanding the people, the process, the system and the result that actually matters.',
                'steps' => [
                    ['label' => '01 / Understand', 'title' => 'Find the real problem.', 'description' => 'Listen to users, management and delivery teams. Separate symptoms from root causes.'],
                    ['label' => '02 / Structure', 'title' => 'Make the work visible.', 'description' => 'Define scope, ownership, priorities, risks, decisions, milestones and reporting.'],
                    ['label' => '03 / Align', 'title' => 'Bring people together.', 'description' => 'Connect business, technology, vendors and leaders around the same practical plan.'],
                    ['label' => '04 / Deliver', 'title' => 'Execute, learn, improve.', 'description' => 'Track outcomes, remove blockers, validate early and leave the organization stronger.'],
                ],
            ],
            'fields' => [
                ['name' => 'section_index', 'label' => 'Section label', 'type' => 'text'],
                ['name' => 'title', 'label' => 'Title', 'type' => 'text'],
                ['name' => 'description', 'label' => 'Introduction', 'type' => 'textarea', 'rows' => 4],
                [
                    'name' => 'steps', 'label' => 'Working method', 'type' => 'collection',
                    'fields' => [
                        ['name' => 'label', 'label' => 'Step label', 'type' => 'text'],
                        ['name' => 'title', 'label' => 'Step title', 'type' => 'text'],
                        ['name' => 'description', 'label' => 'Step description', 'type' => 'textarea', 'rows' => 3],
                    ],
                ],
            ],
        ],

        'global' => [
            'label' => 'Cross-Border Perspective',
            'description' => 'International experience introduction, country labels and map caption.',
            'icon' => 'globe',
            'defaults' => [
                'section_index' => '08 · Cross-border perspective',
                'title' => 'Local context. International exposure.',
                'description' => 'Experience across Bangladesh, China and African rollout environments taught me that systems only work when they respect how people really operate.',
                'countries' => [
                    ['name' => 'Bangladesh'],
                    ['name' => 'China'],
                    ['name' => 'Sierra Leone'],
                    ['name' => 'Liberia'],
                    ['name' => 'International remote work'],
                ],
                'caption_title' => 'Business, technology and people do not speak separate languages.',
                'caption_description' => 'Strong delivery connects all three. That belief has shaped my work across enterprise, development, e-commerce, government and manufacturing environments.',
            ],
            'fields' => [
                ['name' => 'section_index', 'label' => 'Section label', 'type' => 'text'],
                ['name' => 'title', 'label' => 'Title', 'type' => 'text'],
                ['name' => 'description', 'label' => 'Introduction', 'type' => 'textarea', 'rows' => 4],
                [
                    'name' => 'countries', 'label' => 'Country tags', 'type' => 'collection',
                    'fields' => [['name' => 'name', 'label' => 'Country / location', 'type' => 'text']],
                ],
                ['name' => 'caption_title', 'label' => 'Map caption title', 'type' => 'text'],
                ['name' => 'caption_description', 'label' => 'Map caption description', 'type' => 'textarea', 'rows' => 3],
            ],
        ],

        'testimonials' => [
            'label' => 'Testimonials',
            'description' => 'Section title and testimonial slider content.',
            'icon' => 'quote',
            'defaults' => [
                'section_index' => '09 · What people say',
                'title' => 'Leadership is visible in the people around you.',
                'items' => [
                    ['quote' => 'Aminul Bhai isn’t just a leader — he’s the architect of careers.', 'initials' => 'RN', 'name' => 'Razit Nihal', 'role' => 'Project Manager & Product Owner'],
                    ['quote' => 'The best mentor I have had. His guidance shaped my professional journey and strengthened my ethical standards.', 'initials' => 'SA', 'name' => 'Sabbir Ahmed, PMP®', 'role' => 'Senior Project Manager, KONA Software Lab'],
                    ['quote' => 'Excellent at communication, documentation and structured execution. He is helpful, empathetic and committed to his team.', 'initials' => 'FJ', 'name' => 'Fatema Tuj Jahra', 'role' => 'Technical Lead'],
                    ['quote' => 'A natural leader with superb problem-solving and team-building skills. He brings out the best in each project member.', 'initials' => 'RI', 'name' => 'Md. Rakibul Islam', 'role' => 'Head of Releases'],
                    ['quote' => 'He can balance stakeholder expectations with project progress and knows how to protect the key factors for project success.', 'initials' => 'MZ', 'name' => 'Mohammad Zobaer Al Zoha', 'role' => 'ISMS Lead Auditor · CMMI'],
                ],
            ],
            'fields' => [
                ['name' => 'section_index', 'label' => 'Section label', 'type' => 'text'],
                ['name' => 'title', 'label' => 'Title', 'type' => 'text'],
                [
                    'name' => 'items', 'label' => 'Testimonials', 'type' => 'collection',
                    'fields' => [
                        ['name' => 'quote', 'label' => 'Quote', 'type' => 'textarea', 'rows' => 4],
                        ['name' => 'initials', 'label' => 'Initials', 'type' => 'text'],
                        ['name' => 'name', 'label' => 'Person name', 'type' => 'text'],
                        ['name' => 'role', 'label' => 'Role / organization', 'type' => 'text'],
                    ],
                ],
            ],
        ],

        'mentorship' => [
            'label' => 'Mentorship & Training',
            'description' => 'Main mentorship statement and the four supporting cards.',
            'icon' => 'users',
            'defaults' => [
                'section_index' => '10 · Mentorship & training',
                'title' => 'Knowledge is an Amanah. Sharing it is part of the work.',
                'description' => 'I have trained and mentored professionals in PMP®, Agile, business analysis, PMO practices, communication, leadership and project tools. Many now contribute at organizations such as bKash, Pathao, KONA and ShareTrip.',
                'cards' => [
                    ['label' => 'Formal training', 'title' => 'PMP® & project management', 'description' => 'Exam preparation, practical application and career mentoring.'],
                    ['label' => 'Delivery capability', 'title' => 'Agile, hybrid & PMO', 'description' => 'Practical governance, ceremonies, reporting, risk and stakeholder work.'],
                    ['label' => 'Professional growth', 'title' => 'Leadership & communication', 'description' => 'Helping people become clearer, more accountable and more confident.'],
                    ['label' => 'Impact', 'title' => '300+ professionals', 'description' => 'Across training centers, corporate programs, universities and one-to-one mentoring.'],
                ],
            ],
            'fields' => [
                ['name' => 'section_index', 'label' => 'Section label', 'type' => 'text'],
                ['name' => 'title', 'label' => 'Title', 'type' => 'text'],
                ['name' => 'description', 'label' => 'Introduction', 'type' => 'textarea', 'rows' => 5],
                [
                    'name' => 'cards', 'label' => 'Mentorship cards', 'type' => 'collection',
                    'fields' => [
                        ['name' => 'label', 'label' => 'Card label', 'type' => 'text'],
                        ['name' => 'title', 'label' => 'Card title', 'type' => 'text'],
                        ['name' => 'description', 'label' => 'Card description', 'type' => 'textarea', 'rows' => 3],
                    ],
                ],
            ],
        ],

        'credentials' => [
            'label' => 'Credentials',
            'description' => 'Certifications, education, learning tags and the animated tools ribbon.',
            'icon' => 'award',
            'defaults' => [
                'section_index' => '11 · Credentials',
                'title' => 'Formal learning, practical judgment.',
                'description' => 'Certifications matter. They are useful when combined with field experience, business understanding and the humility to keep learning.',
                'certifications' => [
                    ['label' => 'Certification', 'title' => 'PMP®', 'description' => 'Project Management Professional, Project Management Institute. Certified since 2016.', 'logo' => null, 'logo_type' => 'pmp'],
                    ['label' => 'Certification', 'title' => 'CSM®', 'description' => 'Certified ScrumMaster, Scrum Alliance. Agile facilitation and team delivery practice.', 'logo' => null, 'logo_type' => 'csm'],
                ],
                'education_label' => 'Education & continued learning',
                'education_title' => 'BBA in Finance · United International University',
                'education_description' => 'Merit scholarship recipient and champion team member of the Citi Financial IT Case Competition. Continued development in product management, Agile, design thinking and digital transformation.',
                'education_logo' => null,
                'education_logo_type' => 'uiu',
                'education_tags' => [
                    ['name' => 'Finance'],
                    ['name' => 'Product Management'],
                    ['name' => 'Agile Meets Design Thinking'],
                    ['name' => 'Digital Transformation'],
                    ['name' => 'Business Analysis'],
                ],
                'tools' => [
                    ['name' => 'Jira', 'description' => 'Delivery visibility', 'logo' => null, 'logo_type' => 'jira'],
                    ['name' => 'MS Project', 'description' => 'Planning & control', 'logo' => null, 'logo_type' => 'ms-project'],
                    ['name' => 'Confluence', 'description' => 'Knowledge & alignment', 'logo' => null, 'logo_type' => 'confluence'],
                    ['name' => 'Microsoft Excel', 'description' => 'Analysis & reporting', 'logo' => null, 'logo_type' => 'excel'],
                    ['name' => 'Power BI', 'description' => 'Reporting & insight', 'logo' => null, 'logo_type' => 'power-bi'],
                    ['name' => 'Agile · Hybrid · Waterfall', 'description' => 'Context-based methods', 'logo' => null, 'logo_type' => 'methodology'],
                ],
            ],
            'fields' => [
                ['name' => 'section_index', 'label' => 'Section label', 'type' => 'text'],
                ['name' => 'title', 'label' => 'Title', 'type' => 'text'],
                ['name' => 'description', 'label' => 'Introduction', 'type' => 'textarea', 'rows' => 4],
                [
                    'name' => 'certifications', 'label' => 'Certifications', 'type' => 'collection',
                    'fields' => [
                        ['name' => 'label', 'label' => 'Card label', 'type' => 'text'],
                        ['name' => 'title', 'label' => 'Certification title', 'type' => 'text'],
                        ['name' => 'description', 'label' => 'Certification description', 'type' => 'textarea', 'rows' => 3],
                        ['name' => 'logo', 'label' => 'Certification logo/image', 'type' => 'image', 'help' => 'Upload a PNG, JPG or WebP logo. When empty, the selected fallback mark is used.'],
                        [
                            'name' => 'logo_type',
                            'label' => 'Certification mark',
                            'type' => 'select',
                            'options' => [
                                'pmp' => 'PMP mark',
                                'csm' => 'ScrumMaster mark',
                                'award' => 'Generic award mark',
                            ],
                        ],
                    ],
                ],
                ['name' => 'education_label', 'label' => 'Education card label', 'type' => 'text'],
                ['name' => 'education_title', 'label' => 'Education title', 'type' => 'text'],
                ['name' => 'education_description', 'label' => 'Education description', 'type' => 'textarea', 'rows' => 4],
                ['name' => 'education_logo', 'label' => 'Education logo/image', 'type' => 'image', 'help' => 'Upload the institution logo or crest. When empty, the selected fallback mark is used.'],
                [
                    'name' => 'education_logo_type',
                    'label' => 'Education mark',
                    'type' => 'select',
                    'options' => [
                        'uiu' => 'University crest',
                        'education' => 'Generic education mark',
                    ],
                ],
                [
                    'name' => 'education_tags', 'label' => 'Education tags', 'type' => 'collection',
                    'fields' => [['name' => 'name', 'label' => 'Tag', 'type' => 'text']],
                ],
                [
                    'name' => 'tools', 'label' => 'Tools and methods', 'type' => 'collection',
                    'fields' => [
                        ['name' => 'name', 'label' => 'Name', 'type' => 'text'],
                        ['name' => 'description', 'label' => 'Description', 'type' => 'text'],
                        ['name' => 'logo', 'label' => 'Scrolling logo/image', 'type' => 'image', 'help' => 'Upload a transparent PNG, JPG or WebP. When empty, the selected fallback mark is used.'],
                        [
                            'name' => 'logo_type',
                            'label' => 'Tool mark',
                            'type' => 'select',
                            'options' => [
                                'jira' => 'Jira',
                                'ms-project' => 'Microsoft Project',
                                'confluence' => 'Confluence',
                                'excel' => 'Microsoft Excel',
                                'power-bi' => 'Power BI',
                                'methodology' => 'Agile / Hybrid / Waterfall',
                                'generic' => 'Generic tool mark',
                            ],
                        ],
                    ],
                ],
            ],
        ],

        'contact' => [
            'label' => 'Contact',
            'description' => 'Contact statement, links and footer copy.',
            'icon' => 'mail',
            'defaults' => [
                'section_index' => '12 · Next conversation',
                'title_prefix' => 'Have a complex project that needs',
                'title_emphasis' => 'clarity?',
                'description' => 'I work with leaders and teams on ERP, project recovery, PMO setup, product delivery, business analysis, technology planning and professional capability. The first conversation can simply be about understanding the real problem.',
                'links' => [
                    ['label' => 'Email', 'text' => 'aminul@itqanconsulting.com', 'url' => 'mailto:aminul@itqanconsulting.com'],
                    ['label' => 'LinkedIn', 'text' => 'linkedin.com/in/starpmaminul', 'url' => 'https://www.linkedin.com/in/starpmaminul'],
                    ['label' => 'Consulting', 'text' => 'itqanconsulting.com', 'url' => 'https://itqanconsulting.com'],
                    ['label' => 'Phone / WhatsApp', 'text' => '+880 1742 110660', 'url' => 'tel:+8801742110660'],
                ],
                'footer_identity' => 'Md Aminul Islam, PMP®, CSM® · Dhaka, Bangladesh',
                'footer_quote' => '“And whatever good you put forward for yourselves — you will find it with Allah.” · Al-Baqarah 2:110',
            ],
            'fields' => [
                ['name' => 'section_index', 'label' => 'Section label', 'type' => 'text'],
                ['name' => 'title_prefix', 'label' => 'Title', 'type' => 'text'],
                ['name' => 'title_emphasis', 'label' => 'Emphasized title word', 'type' => 'text'],
                ['name' => 'description', 'label' => 'Contact introduction', 'type' => 'textarea', 'rows' => 5],
                [
                    'name' => 'links', 'label' => 'Contact links', 'type' => 'collection',
                    'fields' => [
                        ['name' => 'label', 'label' => 'Link label', 'type' => 'text'],
                        ['name' => 'text', 'label' => 'Displayed text', 'type' => 'text'],
                        ['name' => 'url', 'label' => 'Link URL', 'type' => 'text', 'rules' => ['starts_with:http://,https://,mailto:,tel:'], 'help' => 'Supports https://, mailto: and tel: links.'],
                    ],
                ],
                ['name' => 'footer_identity', 'label' => 'Footer identity', 'type' => 'text'],
                ['name' => 'footer_quote', 'label' => 'Footer quote', 'type' => 'textarea', 'rows' => 3],
            ],
        ],
    ],
];
